### ISSUE TITLE
ImageBrightenConfig.h is missing

### ISSUE THREAD

**Issue by heuristicus** [unr-arl/image_brighten_ros#3]
I just cloned the main branch and can't build because `ImageBrightenConfig.h` doesn't seem to exist. Am I missing something? I can't see this file anywhere in the repository.

Here's the compiler error:

```
Errors     << image_brighten:make /home/subt/subt_ws/logs/image_brighten/build.make.001.log                                                                                                                        
In file included from /home/subt/subt_ws/src/image_brighten_ros/src/image_brighten.cpp:1:
/home/subt/subt_ws/src/image_brighten_ros/include/image_brighten/image_brighten.h:9:10: fatal error: image_brighten/ImageBrightenConfig.h: No such file or directory
    9 | #include <image_brighten/ImageBrightenConfig.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/image_brighten.dir/build.make:63: CMakeFiles/image_brighten.dir/src/image_brighten.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:331: CMakeFiles/image_brighten.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

```
I didn't come across this problem when trying to build this package a few weeks ago.

**Comment by fmascarich** [comment]
@heuristicus I just cloned master into an empty workspace and the package built just fine. 

`ImageBrightenConfig.h` is the ros dynamic reconfigure header generated [here](https://github.com/ntnu-arl/image_brighten_ros/blob/306a017e2f810d18618767759ed8671d0b5f1be5/CMakeLists.txt#L24-L27) in the cmake. Therefore it should only exist as part of the build files and not as part of the source. 

May I ask how are you building this package?

**Comment by heuristicus** [comment]
I checked this today, and confirmed that when building the package by itself it builds without issue.

However, I was building this with multiple metapackages and non-metapackages at the same time. `image_brighten` is a dependency of one of the metapackages. It seems this issue is a quirk of trying to build with metapackages, so I don't think there's any action to be taken.

**Comment by marco-tranzatto** [comment]
@fmascarich  I've got the same problem that appears then `image_brighten` is a dependency of another pkg. Can it be that the dynamic reconfigure part in the Cmake does not work as expected? 

FYI @Samu24  @patripfr To keep in mind when compiling on Kraken

**Comment by fmascarich** [comment]
I am still unable to reproduce this error even when building when it is listed as a dependency of another package. However I've added the project targets as dependencies for the library itself and the generated nodelet (which I believe is when this issue started occuring) in [this branch](https://github.com/ntnu-arl/image_brighten_ros/tree/fix/dyn_reconf_headers_not_gen).
